server:
  port: 8080
  error:
    include-message: always
    whitelabel:
      enabled: false

spring:
  config:
    import:
      - secret.yaml
  application:
    name: LLMka
  main:
    banner-mode: "console" # Disable the startup banner    console/log/off


management:
  endpoints:
    web.exposure.include: "*"
    health:
      show-details: always
      show-components: always

logging:
  config: classpath:log4j2.xml
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.integration: INFO
    org.springframework.messaging: INFO
    com.fbytes.LLMka: DEBUG

llmka:
  config:
    ignore_invalid_config: true
    mappings_file: "${secret.config.mappings_file}"
  embedding:
    model_path: ${secret.embedding.model_path}
    tokenizer_path: ${secret.embedding.tokenizer_path}
    segment_length_limit: 512
    segment_overlap: 128
  datastore:
    save_interval: PT5M
    store_extension: ".json"
    store_path: ${secret.datastore.store_path}
  datacheck:
    metahash_size_limit: 512
    metahash_size_core: 384
    score_limit: 0.87
    reject:
      reject_reason_header: "RejectReason"
      reject_explain_header: "RejectExplain"
  newssource:
    config_folder: ${secret.datasource.config_folder}
  herald:
    news_group_header: "newsGroupHeader"
    config_file: ${secret.telegram.config_file}
    default_queue_size: 200
    telegram:
      poll_delay: 30
      bot:
        botparams:
          israeldigestrusbot:
            tgChannel: "${secret.telegram.bot.israeldigestrusbot.tgChannel}"
            token: "${secret.telegram.bot.israeldigestrusbot.token}"
          aigestbot:
            tgChannel: "${secret.telegram.bot.aigestbot.tgChannel}"
            token: "${secret.telegram.bot.aigestbot.token}"
